name: release-tag

on:
  push:
    tags: [ '[0-9]+.[0-9]+.[0-9]+' ]

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    name: Build and Push
    strategy:
      matrix:
        runner: [buildjet-2vcpu-ubuntu-2204-arm, buildjet-2vcpu-ubuntu-2204]
        include:
          - runner: buildjet-2vcpu-ubuntu-2204
            platform: linux/amd64
    runs-on: ${{ matrix.runner }}
    
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          # Create a new builder instance
          install: true
          driver-opts: |
            image=moby/buildkit:latest
          buildkitd-flags: --debug

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.platform }}
          push: true
          tags: ghcr.io/krateoplatformops/krateo-frontend:2.1.30